### ISSUE TITLE
Contact

### ISSUE THREAD

**Issue by Angelica137** [fac31/Agency_AR#5]
As a user, when I want to hire a developer
I want to be able to get in touch with the agency
so that I can hire them

AC
Form should have validation 
mandatory fields - user should not be able to submit if not complete

**Comment by Angelica137** [comment]
https://drive.google.com/file/d/1fXdKhpBA0pi0Nk7ju3qCGYXnGPphBrHy/view?usp=sharing

**Comment by RGHANILOO** [comment]
contact looks great but i was thinking maybe instead of having radio group for mr,mrs, other, we could just either a drop down or a checkbox, With radio buttons user can select more than one option.
checkbox user can only select one.

**Comment by Angelica137** [comment]
hey, it is the other way around. Radio buttons only can select one, checkbox can select many.

We can have the drop down if you like. We just need to raise a ticket and prioritise it. I think first we finish the required functionality and then we can change it?

**Comment by RGHANILOO** [comment]
sorry you are correct.
i was just poking around and misworded it .
<img width="528" alt="Screenshot 2024-03-23 at 10 50 32" src="https://github.com/fac31/Agency_AR/assets/26300368/c2474a0b-477f-4fb5-97f0-da8bf44aff2c">

> I think first we finish the required functionality and then we can change it?
i agree we can go back to it after
